# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0002_shoppingitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
