# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0003_auto_20190130_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
    ]
